name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.STORE_FILE_BASE64 }}" | base64 --decode > app/keystore.jks
      - name: Build with Gradle
        env:
          STORE_FILE: keystore.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk WebWakeDroid.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: WebWakeDroid.apk
          name: WebWake Droid ${{ github.ref_name }}
          body: |
            ![Downloads](https://img.shields.io/github/downloads/${{ github.repository }}/${{ github.ref_name }}/total.svg)

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref }}
